spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=false;sendStringParametersAsUnicode=false;
    username: demo_user # Please manually create it by running the SQL script in ./db/manual-init.sql
                        # I tried to set it up in docker-compose, but it doesn't work, and I don't want to wast too much time on it, so just create it manually.
    password: Password1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connection-timeout: 2000
      validation-timeout: 1000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
    open-in-view: false
spring.flyway.enabled: true
spring.flyway.locations: classpath:db/migration

logging.level.org.flywaydb: DEBUG