spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=false;sendStringParametersAsUnicode=false;
    username: sa
    password: Password1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
    open-in-view: false
spring.flyway.enabled: true
spring.flyway.locations: classpath:db/migration

logging.level.org.flywaydb: DEBUG