spring:
  datasource:
    #The DB name cannot contains hyphen character "-", you should use underscore character "_".
    url: jdbc:mysql://localhost:3306/practice10-transaction-simple?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: user
    #HikariCP: the connection pool framework: http://www.baeldung.com/hikaricp
    hikari:
      pool-name: practice10-transaction-simple-pool

    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
#    show-sql: true
    properties:
      hibernate.format_sql: true

      # This config must match with Dialect config in TransactionalOutboxConfig.persistor()
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    # Avoid accidental performance issue: https://github.com/spring-projects/spring-boot/issues/7107
    open-in-view: false
    hibernate:
      ddl-auto: update

  sql:
    init:
      #Account for running schema scripts
      username: root
      password: root

# This can help use to track transaction in log
#logging.level.org.springframework.transaction.interceptor: TRACE

# Log SQL Query with arguments.
logging.level.org.hibernate.SQL: debug
logging.level.org.hibernate.type.descriptor.sql: trace