
spring:
  # The DB Connection to In-Memory DB. Actually you don't need this configuration, they are all in the default configuration.
  # I just put it here to show you how to configure the DB for Batch job. If you comment out the datasource block, the could should still run fine.
  datasource:
    url: jdbc:mysql://localhost:3306/db_example
    username: root
    password: root
    hikari:
      pool-name: json-column-db

  # http://www.baeldung.com/sql-logging-spring-boot
  # While this is extremely simple, it’s not recommended as it directly unloads everything to standard output without any optimizations of a logging framework.
  # Moreover, it doesn’t log the parameters of prepared statements.
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect
    # there is quite a history behind this setting https://github.com/spring-projects/spring-boot/issues/7107
    open-in-view: false
    hibernate:
      ddl-auto: create
