
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=false;sendStringParametersAsUnicode=false;
    username: sa
    password: Password1

    # This configuration will make Spring Boot start the `schema.sql` file.
    # Ref: https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto-database-initialization
    # Execute all schema_*.sql when starting the application.
    # Ref: https://www.baeldung.com/spring-boot-sql-import-files
#    data: schema_*.sql

  jpa:
    # Disabled it to avoid unexpected performance issue: https://www.baeldung.com/spring-open-session-in-view
    open-in-view: false
    generate-ddl: false
    hibernate:
      # On Production, we should use Flyway instead
      ddl-auto: none
  sql:
    init:
      mode: always
#    #The platform for DDL or DML scripts (it's all by default)
##    platform: mysql
#
#    #HikariCP: the connection pool framework: http://www.baeldung.com/hikaricp
#    hikari:
#      pool-name: practice-spring-jpa
#


