
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=master
    username: sa
    password: Password1

  jpa:
    # Disabled it to avoid unexpected performance issue: https://www.baeldung.com/spring-open-session-in-view
    open-in-view: false

#    #The platform for DDL or DML scripts (it's all by default)
##    platform: mysql
#
#    #HikariCP: the connection pool framework: http://www.baeldung.com/hikaricp
#    hikari:
#      pool-name: practice-spring-jpa
#
