services:
  demo-sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1
    expose:
      - "1433"
    ports:
      - "1433:1433"