version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_practice_spring_jpa
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-practice_spring_jpa_db}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-user}

#    # View more at https://github.com/abagayev/docker-bootstrap-collection/blob/master/mysql-few-databases/docker-compose.yml
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    volumes:
#      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d