spring:
    datasource:
        url: jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=false;sendStringParametersAsUnicode=false;
        username: sa
        password: Password1
        hikari:
            leak-detection-threshold: 5000
            connection-timeout: 5000
            maximum-pool-size: 5
    jpa:
        # Disabled it to avoid unexpected performance issue: https://www.baeldung.com/spring-open-session-in-view
        open-in-view: false
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                generate_statistics: false # Enable it if you want to check verbose metrics
        show-sql: true

