
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=master
    username: sa
    password: Password1

    # Execute all schema_*.sql when starting the application.
    # Ref: https://www.baeldung.com/spring-boot-sql-import-files
#    data: schema_*.sql

  jpa:
    # Disabled it to avoid unexpected performance issue: https://www.baeldung.com/spring-open-session-in-view
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      #    show-sql: true
      hibernate.format_sql: true

      # This config must match with Dialect config in TransactionalOutboxConfig.persistor()
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect


